/// Scanner — walks a directory tree and identifies AI code patterns.
/// Pure static analysis: no code execution, no imports, just file reading.
use anyhow::Result;
use std::fs;
use std::path::{Path, PathBuf};

// ── MCP transport type ────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
pub enum McpTransport {
    /// HTTP + Server-Sent Events (legacy, pre-2025 MCP spec)
    Sse,
    /// Streamable HTTP (MCP spec 2025, recommended)
    StreamableHttp,
    /// Subprocess stdin/stdout
    Stdio,
}

impl std::fmt::Display for McpTransport {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            McpTransport::Sse => write!(f, "SSE"),
            McpTransport::StreamableHttp => write!(f, "Streamable HTTP"),
            McpTransport::Stdio => write!(f, "Stdio"),
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum McpFramework {
    /// @rekog/mcp-nest — NestJS decorator-based wrapper
    ReKogMcpNest,
    /// Raw @modelcontextprotocol/sdk — manual server.tool() wiring
    RawSdk,
    /// fastmcp / mcp Python library
    FastMcp,
    /// Unknown MCP implementation
    Unknown,
}

// ── Public types ──────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub struct Finding {
    /// Absolute path to the file that triggered this finding
    pub path: String,
    /// What we detected
    pub kind: FindingKind,
    /// Which keywords fired (for display)
    pub signals: Vec<String>,
}

impl Finding {
    pub fn description(&self) -> String {
        match &self.kind {
            FindingKind::EvalRunner { language, .. } => format!(
                "{language} eval runner — {} signal(s): {}",
                self.signals.len(),
                self.signals.join(", ")
            ),
            FindingKind::NL2Sql { function_name, .. } => {
                format!("NL2SQL validator — fn `{function_name}`")
            }
            FindingKind::RagPipeline { components } => {
                format!("RAG pipeline — {}", components.join(" + "))
            }
            FindingKind::AiService { provider } => format!("AI service — {provider}"),
            FindingKind::McpServer {
                framework,
                transports,
                tool_count,
                server_name,
                is_root,
            } => {
                let fw = match framework {
                    McpFramework::ReKogMcpNest => "@rekog/mcp-nest",
                    McpFramework::RawSdk => "@modelcontextprotocol/sdk",
                    McpFramework::FastMcp => "fastmcp",
                    McpFramework::Unknown => "unknown",
                };
                let tp = transports
                    .iter()
                    .map(|t| t.to_string())
                    .collect::<Vec<_>>()
                    .join(" + ");
                let name = server_name
                    .as_deref()
                    .map(|n| format!(" \"{n}\""))
                    .unwrap_or_default();
                let role = if *is_root { "[root]" } else { "[tool]" };
                format!("MCP {role}{name} ({fw}) — {tool_count} tool(s) — transport: {tp}")
            }
        }
    }
}

#[derive(Debug, Clone)]
pub enum FindingKind {
    /// A file that runs eval cases and prints pass/fail to stdout
    EvalRunner {
        language: Language,
        /// Inferred command to run this file (e.g. `["npx","ts-node","-P","..."]`)
        run_cmd: Vec<String>,
        /// Nearby tsconfig path (TypeScript only)
        #[allow(dead_code)]
        tsconfig: Option<String>,
        /// Estimated number of test cases in the file
        test_count: Option<usize>,
        /// Pattern the pass/fail summary line matches (to use in assertions)
        summary_pat: String,
    },
    /// A function that validates / sanitizes SQL generated by an AI agent
    NL2Sql {
        language: Language,
        function_name: String,
        file_path: String,
        /// Nearest tsconfig that covers this file
        tsconfig: Option<String>,
        /// Allowed schemas extracted from source (e.g. ["public","analytics"])
        allowed_schemas: Vec<String>,
    },
    /// Embedding + vector-store pipeline
    RagPipeline {
        components: Vec<String>, // e.g. ["ONNX embeddings", "USearch HNSW"]
    },
    /// Generic LLM service (Bedrock, OpenAI, etc.)
    AiService { provider: String },
    /// MCP (Model Context Protocol) server definition
    McpServer {
        framework: McpFramework,
        /// Which transports are active (may be multiple)
        transports: Vec<McpTransport>,
        /// Number of @Tool / server.tool() definitions found in this file
        tool_count: usize,
        /// Server name from McpModule.forRoot / new Server() config
        server_name: Option<String>,
        /// true = server registration/main file (McpModule.forRoot, new Server() + transport,
        ///        mcp.run()); false = tool-definition-only file.
        /// Generator uses this to emit ONE suite per server and aggregate tool counts.
        is_root: bool,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum Language {
    TypeScript,
    Python,
    Unknown,
}

impl std::fmt::Display for Language {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Language::TypeScript => write!(f, "TypeScript"),
            Language::Python => write!(f, "Python"),
            Language::Unknown => write!(f, "Unknown"),
        }
    }
}

// ── Entry point ───────────────────────────────────────────────────────────────

/// Walk `dir` and return all AI-relevant findings.
pub fn scan(dir: &str) -> Result<Vec<Finding>> {
    let root = Path::new(dir);
    let mut findings = Vec::new();

    let files = collect_source_files(root);

    for path in &files {
        let rel = path
            .strip_prefix(root)
            .unwrap_or(path)
            .display()
            .to_string();
        let lang = detect_language(path);
        let content = match fs::read_to_string(path) {
            Ok(c) => c.to_lowercase(),
            Err(_) => continue,
        };

        // ── Eval runner detection ─────────────────────────────────────────
        let eval_signals = eval_runner_signals(&content, &rel);
        if eval_signals.len() >= 2 {
            let tsconfig = find_nearest_tsconfig(path, root);
            let run_cmd = infer_run_cmd(path, &tsconfig, &lang);
            let test_count = estimate_test_count(&content, &lang);
            let summary_pat = infer_summary_pattern(&content);
            findings.push(Finding {
                path: path.display().to_string(),
                signals: eval_signals,
                kind: FindingKind::EvalRunner {
                    language: lang.clone(),
                    run_cmd,
                    tsconfig,
                    test_count,
                    summary_pat,
                },
            });
            continue; // one finding per file
        }

        // ── NL2SQL function detection ─────────────────────────────────────
        if let Some(fn_name) = detect_nl2sql_function(&content) {
            let tsconfig = find_nearest_tsconfig(path, root);
            let allowed_schemas = extract_allowed_schemas(&content);
            findings.push(Finding {
                path: path.display().to_string(),
                signals: vec![fn_name.clone()],
                kind: FindingKind::NL2Sql {
                    language: lang.clone(),
                    function_name: fn_name,
                    file_path: path.display().to_string(),
                    tsconfig,
                    allowed_schemas,
                },
            });
            continue;
        }

        // ── RAG pipeline detection ────────────────────────────────────────
        let rag_components = detect_rag_components(&content);
        if !rag_components.is_empty() {
            findings.push(Finding {
                path: path.display().to_string(),
                signals: rag_components.clone(),
                kind: FindingKind::RagPipeline {
                    components: rag_components,
                },
            });
            continue;
        }

        // ── MCP server detection ──────────────────────────────────────────
        if let Some(mcp) = detect_mcp_server(&content) {
            let mut signals = mcp
                .transports
                .iter()
                .map(|t| t.to_string())
                .collect::<Vec<_>>();
            if mcp.is_root {
                signals.push("root".into());
            }
            findings.push(Finding {
                path: path.display().to_string(),
                signals,
                kind: FindingKind::McpServer {
                    framework: mcp.framework,
                    transports: mcp.transports,
                    tool_count: mcp.tool_count,
                    server_name: mcp.server_name,
                    is_root: mcp.is_root,
                },
            });
            continue;
        }

        // ── Generic AI service detection ──────────────────────────────────
        if let Some(provider) = detect_ai_provider(&content) {
            findings.push(Finding {
                path: path.display().to_string(),
                signals: vec![provider.clone()],
                kind: FindingKind::AiService { provider },
            });
        }
    }

    // De-duplicate: if a file was flagged as both eval runner and AI service,
    // keep only the more specific finding (already handled by `continue` above).
    Ok(findings)
}

// ── File collection ───────────────────────────────────────────────────────────

fn collect_source_files(root: &Path) -> Vec<PathBuf> {
    let skip = [
        // JS/TS
        "node_modules",
        "dist",
        ".next",
        "coverage",
        "build",
        ".turbo",
        "vendor",
        // Rust
        "target",
        // Git
        ".git",
        // Python virtual envs — many naming conventions
        ".env",
        "env",
        "venv",
        ".venv",
        "virtualenv",
        // Python bytecode / package installs
        "__pycache__",
        "site-packages",
        "dist-packages",
        ".eggs",
        "egg-info",
        // Misc
        ".tox",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
    ];
    let ext = ["ts", "tsx", "js", "py", "mjs", "cjs"];

    let mut out = Vec::new();
    collect_recursive(root, &skip, &ext, &mut out);
    out
}

fn collect_recursive(dir: &Path, skip: &[&str], exts: &[&str], out: &mut Vec<PathBuf>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");

        // Skip noise directories
        if path.is_dir() {
            if skip.contains(&name) {
                continue;
            }
            collect_recursive(&path, skip, exts, out);
        } else if path.is_file() {
            // Skip type-declaration files — they duplicate signals
            if name.ends_with(".d.ts") {
                continue;
            }
            if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
                if exts.contains(&ext) {
                    out.push(path);
                }
            }
        }
    }
}

// ── Language detection ────────────────────────────────────────────────────────

fn detect_language(path: &Path) -> Language {
    match path.extension().and_then(|e| e.to_str()) {
        Some("ts" | "tsx") => Language::TypeScript,
        Some("py") => Language::Python,
        _ => Language::Unknown,
    }
}

// ── Eval runner signals ───────────────────────────────────────────────────────

/// Returns matched signal names. ≥2 signals = confident eval runner.
fn eval_runner_signals(content: &str, rel_path: &str) -> Vec<String> {
    let mut sigs = Vec::new();

    // File-name hint (strong)
    let basename = rel_path.split('/').next_back().unwrap_or(rel_path);
    if basename.contains("eval") || basename.contains("spec") || basename.contains("test") {
        sigs.push("eval-filename".into());
    }

    // Pass/fail counting patterns
    if content.contains("passed++") || content.contains("failed++") {
        sigs.push("pass-fail-counter".into());
    }
    if content.contains("passed +=") || content.contains("failures.push") {
        sigs.push("failure-list".into());
    }

    // Visible check/cross markers in output
    if content.contains("✓") || content.contains("✗") || content.contains("\\u2713") {
        sigs.push("check-marks".into());
    }

    // Summary line pattern
    if content.contains("results:") || content.contains("passed (") || content.contains("% passed")
    {
        sigs.push("summary-line".into());
    }

    // Assertion helper pattern
    if content.contains("function assert(")
        || content.contains("const assert ")
        || content.contains("def assert_equal")
        || content.contains("assertrejects")
    {
        sigs.push("assert-helper".into());
    }

    // process.exit at the end (common for test runners)
    if content.contains("process.exit(") {
        sigs.push("process-exit".into());
    }

    sigs
}

/// Count eval test cases by looking for the pattern used inside eval case arrays.
/// TypeScript: `{ name:` or `name: '` inside an array literal
/// Python:     `{"name":` or `"name":` inside a list
fn estimate_test_count(content: &str, lang: &Language) -> Option<usize> {
    // Count lines with a `run:` or `run: async` key — each is one eval case in TS
    let ts_case = content.matches("run: async").count()
        + content.matches("run:async").count()
        + content.matches("run: ()").count();
    // Python: each `"name":` inside a list item
    let py_case = content.matches("\"name\":").count();

    let count = match lang {
        Language::TypeScript => ts_case,
        Language::Python => py_case,
        Language::Unknown => 0,
    };
    if count > 0 {
        Some(count)
    } else {
        None
    }
}

/// Find the summary line pattern the eval runner prints (to use in the assertion)
fn infer_summary_pattern(content: &str) -> String {
    // Common patterns, ordered by specificity
    for pat in &["passed (", "passed\n", "/", "results:"] {
        if content.contains(pat) {
            return pat.to_string();
        }
    }
    "passed".into()
}

// ── Tsconfig / run command inference ─────────────────────────────────────────

/// Walk up from `file` toward `root` looking for tsconfig.json
fn find_nearest_tsconfig(file: &Path, root: &Path) -> Option<String> {
    // First: look in the same directory and its direct parent
    let candidates = [
        file.parent().map(|p| p.join("tsconfig.json")),
        file.parent()
            .and_then(|p| p.parent())
            .map(|p| p.join("tsconfig.json")),
        // Also check for an evals-specific tsconfig in the same dir
        file.parent().map(|p| p.join("tsconfig.build.json")),
    ];
    for c in candidates.into_iter().flatten() {
        if c.exists() && c.starts_with(root) {
            return Some(c.display().to_string());
        }
    }
    // Root tsconfig as fallback
    let root_ts = root.join("tsconfig.json");
    if root_ts.exists() {
        return Some(root_ts.display().to_string());
    }
    None
}

/// Build the command to run this file as a subprocess
fn infer_run_cmd(file: &Path, tsconfig: &Option<String>, lang: &Language) -> Vec<String> {
    match lang {
        Language::TypeScript => {
            let mut cmd = vec!["npx".into(), "ts-node".into()];
            if let Some(tc) = tsconfig {
                cmd.push("-P".into());
                cmd.push(tc.clone());
            }
            // Do NOT add --transpile-only: projects with tsconfig paths/baseUrl
            // need full type resolution to resolve aliased imports correctly.
            cmd.push(file.display().to_string());
            cmd
        }
        Language::Python => {
            vec!["python3".into(), file.display().to_string()]
        }
        Language::Unknown => {
            vec!["node".into(), file.display().to_string()]
        }
    }
}

// ── NL2SQL detection ──────────────────────────────────────────────────────────

/// Returns the function name if file defines an NL2SQL validator
fn detect_nl2sql_function(content: &str) -> Option<String> {
    let patterns = [
        ("validateandsanitizesql", "validateAndSanitizeSql"),
        ("validate_and_sanitize_sql", "validate_and_sanitize_sql"),
        ("validatesql", "validateSql"),
        ("sanitizesql", "sanitizeSql"),
        ("nl2sql_security", "nl2sql_security"),
        ("checkquerysecurity", "checkQuerySecurity"),
    ];
    for (needle, canonical) in &patterns {
        // Must be an export/function definition, not just a call site
        if content.contains(&format!("export async function {needle}"))
            || content.contains(&format!("export function {needle}"))
            || content.contains(&format!("def {needle}"))
            || content.contains(&format!("async def {needle}"))
        {
            return Some(canonical.to_string());
        }
    }
    None
}

/// Extract allowed schema names from SQL security source.
/// Looks for common schema name patterns in the source file.
fn extract_allowed_schemas(content: &str) -> Vec<String> {
    let mut schemas = Vec::new();
    // Look for string literals next to "allowed" or "schema" keywords
    let schema_patterns = [
        "public",
        "analytics",
        "data_warehouse",
        "reporting",
        "raw_data",
        "staging",
    ];
    for s in &schema_patterns {
        if content.contains(s) {
            schemas.push(s.to_string());
        }
    }
    schemas
}

// ── RAG component detection ───────────────────────────────────────────────────

fn detect_rag_components(content: &str) -> Vec<String> {
    let mut c = Vec::new();
    macro_rules! check {
        ($label:expr, $($pat:expr),+) => {
            if [$($pat),+].iter().any(|p| content.contains(p)) {
                c.push($label.to_string());
            }
        };
    }
    check!(
        "ONNX embeddings",
        "onnxruntime",
        "ort.inferencesession",
        ".onnx"
    );
    check!(
        "USearch HNSW",
        "usearch",
        "metrickind.cos",
        "ef_construction"
    );
    check!("HNSWlib", "hnswlib", "hnsw");
    check!("FAISS", "faiss", "faissindex");
    check!("Vector DB", "pinecone", "weaviate", "qdrant", "chroma");
    check!(
        "Sentence embeddings",
        "all-minilm",
        "bge-",
        "nomic-embed",
        "text-embedding"
    );
    check!(
        "Retrieval",
        "retriev",
        "vector_search",
        "nearest_neighbor",
        "top_k"
    );
    c
}

// ── AI provider detection ─────────────────────────────────────────────────────

fn detect_ai_provider(content: &str) -> Option<String> {
    macro_rules! provider {
        ($name:expr, $($pat:expr),+) => {
            if [$($pat),+].iter().any(|p| content.contains(p)) {
                return Some($name.to_string());
            }
        };
    }
    provider!("AWS Bedrock", "bedrock-agent-runtime", "invokeagentcommand");
    provider!("OpenAI", "openai", "chatcompletion");
    provider!("Azure OpenAI", "azureopenai", "azure-openai");
    provider!("Anthropic Claude", "anthropic", "claude-");
    provider!("Ollama", "ollama");
    provider!("HuggingFace", "huggingface", "transformers");
    None
}

// ── MCP server detection ──────────────────────────────────────────────────────

struct McpFinding {
    framework: McpFramework,
    transports: Vec<McpTransport>,
    tool_count: usize,
    server_name: Option<String>,
    /// Whether this file is a server-registration root (vs a tool-definition file).
    is_root: bool,
}

/// Returns Some if the file defines or registers an MCP server.
/// Detects framework, active transports, and tool count.
fn detect_mcp_server(content: &str) -> Option<McpFinding> {
    // ── Must have at least one MCP anchor ─────────────────────────────────────
    let is_mcp = content.contains("@modelcontextprotocol/sdk")
        || content.contains("modelcontextprotocol/sdk")
        || content.contains("@rekog/mcp-nest")
        || content.contains("rekog/mcp-nest")
        || content.contains("mcpmodule")
        || content.contains("fastmcp")
        || content.contains("mcp.server.fastmcp")
        // Raw SDK patterns
        || (content.contains("server.tool(") && content.contains("server"))
        || content.contains("listtools requestschema")
        || content.contains("calltoolrequestschema");

    if !is_mcp {
        return None;
    }

    // ── Framework ─────────────────────────────────────────────────────────────
    let framework = if content.contains("@rekog/mcp-nest")
        || content.contains("rekog/mcp-nest")
        || content.contains("mcpmodule")
    {
        McpFramework::ReKogMcpNest
    } else if content.contains("fastmcp")
        || content.contains("mcp.server.fastmcp")
        || content.contains("from mcp import")
    {
        McpFramework::FastMcp
    } else if content.contains("@modelcontextprotocol/sdk")
        || content.contains("modelcontextprotocol/sdk")
        || content.contains("server.tool(")
    {
        McpFramework::RawSdk
    } else {
        McpFramework::Unknown
    };

    // ── Transport detection ───────────────────────────────────────────────────
    let mut transports = Vec::new();

    // Explicit transport config keywords
    let has_sse = content.contains("sseservertransport")
        || content.contains("mcptransporttype.sse")
        || content.contains("sseendpoint")
        || content.contains("mcp-sse")
        || content.contains("mcp_sse_service")
        || content.contains("text/event-stream");

    let has_streamable = content.contains("streamablehttpservertransport")
        || content.contains("mcptransporttype.streamable_http")
        || content.contains("streamablehttp")
        || content.contains("streamable-http")
        || content.contains("mcp-streamable-http");

    let has_stdio = content.contains("stdioservertransport")
        || content.contains("stdioclienttransport")
        || content.contains("mcptransporttype.stdio")
        || content.contains("stdio.service");

    if has_sse {
        transports.push(McpTransport::Sse);
    }
    if has_streamable {
        transports.push(McpTransport::StreamableHttp);
    }
    if has_stdio {
        transports.push(McpTransport::Stdio);
    }

    // ── Default transport inference when no explicit config ───────────────────
    // @rekog/mcp-nest default: SSE + Streamable HTTP (as of v1.x)
    // Raw SDK: stdio is the most common default
    if transports.is_empty() {
        match framework {
            McpFramework::ReKogMcpNest => {
                transports.push(McpTransport::Sse);
                transports.push(McpTransport::StreamableHttp);
            }
            McpFramework::FastMcp => {
                // fastmcp defaults to stdio; can be overridden
                transports.push(McpTransport::Stdio);
            }
            McpFramework::RawSdk | McpFramework::Unknown => {
                transports.push(McpTransport::Stdio);
            }
        }
    }

    // ── Tool count ────────────────────────────────────────────────────────────
    let tool_count = count_mcp_tools(content, &framework);

    // ── Server name ───────────────────────────────────────────────────────────
    let server_name = extract_mcp_server_name(content);

    // ── Root detection ────────────────────────────────────────────────────────
    // A "root" file is the server registration / main entry point.
    // Tool-definition-only files (`@Tool` decorators, `server.tool()` calls but
    // no server wiring) are non-roots and will be merged into the root's suite.
    let is_root = content.contains("mcpmodule.forroot")
        || content.contains("mcpmodule.register(")
        // Raw SDK: creates a Server AND wires up a transport
        || (content.contains("new server(")
            && (content.contains("stdioservertransport")
                || content.contains("sseservertransport")
                || content.contains("streamablehttpservertransport")
                || content.contains("server.connect(")))
        // FastMCP / Python: explicit run call
        || content.contains("mcp.run(")
        || content.contains("server.run(")
        || content.contains("fastmcp(")     // mcp = FastMCP(...)
        // Module bootstrap patterns
        || content.contains("app.listen(")  // Express/Fastify + MCP
        || content.contains("nestfactory.create"); // NestJS bootstrap

    Some(McpFinding {
        framework,
        transports,
        tool_count,
        server_name,
        is_root,
    })
}

/// Count tool definitions in the file.
fn count_mcp_tools(content: &str, framework: &McpFramework) -> usize {
    match framework {
        // @Tool({ name: ... }) decorator — count occurrences
        McpFramework::ReKogMcpNest => {
            content.matches("@tool({").count() + content.matches("@tool( {").count()
        }
        // Python: @mcp.tool or @server.tool decorator
        McpFramework::FastMcp => {
            content.matches("@mcp.tool").count() + content.matches("@server.tool").count()
        }
        // Raw SDK: server.tool("name", ...)
        McpFramework::RawSdk | McpFramework::Unknown => content.matches("server.tool(").count(),
    }
}

/// Try to extract the server name from common config patterns.
/// Handles: `name: "my-server"`, `new Server({ name: "..."`, `name: 'my-server'`
fn extract_mcp_server_name(content: &str) -> Option<String> {
    // Look for: name: "value" or name: 'value' near mcp/server context
    for line in content.lines() {
        let t = line.trim();
        if t.starts_with("name:") || t.contains("\"name\":") {
            // Extract quoted value
            if let Some(v) = extract_quoted_value(t) {
                // Filter out generic/short names that aren't server names
                if v.len() > 2 && !v.starts_with("$.") && !v.contains(' ') || v.contains('-') {
                    return Some(v);
                }
            }
        }
    }
    None
}

fn extract_quoted_value(s: &str) -> Option<String> {
    // Single or double quoted value after a colon or equals
    for delim in &['"', '\''] {
        if let Some(start) = s.find(*delim) {
            if let Some(end) = s[start + 1..].find(*delim) {
                let val = &s[start + 1..start + 1 + end];
                if !val.is_empty() {
                    return Some(val.to_string());
                }
            }
        }
    }
    None
}
